#pragma once
#include "NativeGameplayTags.h"

/** 标签只由本模块原生登记，网络两端保持一致；不在可选资产卸载时删除。 */
namespace GamePlatformAbilityTags
{
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputRoot);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTestPredicted);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTestServer);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blocked);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TestEnabled);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TestDuration);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TestInfinite);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TestCooldown);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TestCue);
    GAMEPLATFORMABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FailureGate);
}
