#pragma once

#include "NativeGameplayTags.h"

namespace DivineBeastsCharacterTags
{
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Rat);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Ox);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Tiger);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Rabbit);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Dragon);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Snake);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Horse);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Goat);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Monkey);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Rooster);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Dog);
    DIVINEBEASTSCHARACTERSRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zodiac_Boar);
}
