#pragma once

#include "NativeGameplayTags.h"

/** MobaPresentationTags（MOBA表现语义标签）。所有标签由MobaPresentationRuntime统一拥有。 */
namespace MobaPresentationTags
{
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Hit);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Critical);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Heal);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Shield_Hit);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Control_Apply);

    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cast_Start);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cast_Release);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Projectile_Spawn);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Area_Warning);

    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Apply);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Remove);

    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Death);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Respawn);

    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arena_Match_Start);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arena_Match_End);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arena_Score_Changed);
    MOBAPRESENTATIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arena_Objective_Completed);
}
