#pragma once

#include "NativeGameplayTags.h"

namespace GamePlatformCombatTags
{
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_AttackPowerCoefficient);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_AbilityPowerCoefficient);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Type);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_CanCritical);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_CriticalRoll);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Healing);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_BypassShield);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Stun);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Silence);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Healing);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Control);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Result_Critical);
    // 历史结果标签保留已发布身份；当前控制流程不再根据数值韧性产生抵抗事件。
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Result_ControlResisted);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Healing);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Control);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death);
}
