#pragma once

#include "NativeGameplayTags.h"

namespace GamePlatformCombatTags
{
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_AttackPowerCoefficient);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_AbilityPowerCoefficient);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Type);
    // 旧暴击数据标签保留已发布名称以保证历史资产标签可识别；当前GameplayEffect不会写入或读取。
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_CanCritical);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_CriticalRoll);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Healing);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_BypassShield);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
    /** State_Shielded（临时护盾效果标签）：只标记GAS限时护盾状态，不定义数值属性。 */
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Shielded);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Stun);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Silence);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Healing);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Control);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);

    // 历史暴击结果标签只作资产兼容，当前战斗不产生暴击结果。
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Result_Critical);
    // 历史结果标签保留已发布身份；当前控制流程不再根据数值韧性产生抵抗事件。
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Result_ControlResisted);

    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Damage);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Healing);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Control);
    GAMEPLATFORMCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death);
}
