#pragma once

#include "NativeGameplayTags.h"

namespace GamePlatformAITags
{
    GAMEPLATFORMAI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Patrol);
    GAMEPLATFORMAI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Investigate);
    GAMEPLATFORMAI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Chase);
    GAMEPLATFORMAI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_ReturnHome);
    GAMEPLATFORMAI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Attack);
}
